services:
  backend:
    build:
      context: ./Backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./Backend:/app
      - backend-deps:/app/node_modules
    env_file: .env
    environment:
      MONGO_URI: "mongodb://mariamramy1074_db_user:Shoyotastic@ac-fu0jurk-shard-00-00.wfwwjwa.mongodb.net:27017,ac-fu0jurk-shard-00-01.wfwwjwa.mongodb.net:27017,ac-fu0jurk-shard-00-02.wfwwjwa.mongodb.net:27017/marketplaceDB?ssl=true&replicaSet=atlas-ef3awd-shard-0&authSource=admin&appName=Cluster0"
      MONGODB_URI: "mongodb://mariamramy1074_db_user:Shoyotastic@ac-fu0jurk-shard-00-00.wfwwjwa.mongodb.net:27017,ac-fu0jurk-shard-00-01.wfwwjwa.mongodb.net:27017,ac-fu0jurk-shard-00-02.wfwwjwa.mongodb.net:27017/marketplaceDB?ssl=true&replicaSet=atlas-ef3awd-shard-0&authSource=admin&appName=Cluster0"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./Frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - frontend-deps:/app/node_modules
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 3000
    depends_on:
      - backend

volumes:
  backend-deps:
  frontend-deps: